# Generated by Django 4.2.1 on 2023-06-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('cargo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('imagen', models.ImageField(default='default.jpg', upload_to='empleados/')),
            ],
        ),
    ]
