# Generated by Django 4.2.2 on 2023-06-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionEmpleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='imagen',
            field=models.ImageField(upload_to='empleados/'),
        ),
    ]
