# Generated by Django 4.2.2 on 2023-06-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionEmpleados', '0002_alter_empleado_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=8),
        ),
    ]
