# Generated by Django 4.2.5 on 2023-09-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloSeguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('dueño', 'Dueño'), ('veterinario', 'Veterinario'), ('personal', 'Personal')], max_length=100),
        ),
    ]
