# Generated by Django 4.2.4 on 2023-10-21 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moduloGestionExpedientes', '0011_alter_expediente_dui'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha_de_examen', models.DateField()),
                ('tipo_muestra', models.CharField(choices=[('sangre', 'Sangre'), ('orina', 'Orina'), ('heces', 'Heces'), ('otro', 'Otro')], max_length=20)),
                ('valores_referencia', models.CharField(max_length=500)),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moduloGestionExpedientes.expediente')),
            ],
        ),
    ]
