# Generated by Django 4.2.4 on 2023-10-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionExpedientes', '0011_alter_expediente_dui'),
        ('moduloGestionExamenLaboratorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examenlaboratorio',
            name='expediente',
        ),
        migrations.AddField(
            model_name='examenlaboratorio',
            name='expediente',
            field=models.ManyToManyField(to='moduloGestionExpedientes.expediente'),
        ),
    ]
