# Generated by Django 4.2.4 on 2023-10-21 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionExpedientes', '0011_alter_expediente_dui'),
        ('moduloGestionExamenLaboratorio', '0002_remove_examenlaboratorio_expediente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examenlaboratorio',
            name='expediente',
        ),
        migrations.AddField(
            model_name='examenlaboratorio',
            name='expediente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moduloGestionExpedientes.expediente'),
        ),
    ]
