# Generated by Django 4.2.5 on 2023-10-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionVacunas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacuna',
            name='cantidad_disponible',
        ),
        migrations.RemoveField(
            model_name='vacuna',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='vacuna',
            name='dosis',
        ),
        migrations.RemoveField(
            model_name='vacuna',
            name='frecuencia',
        ),
        migrations.RemoveField(
            model_name='vacuna',
            name='imagen',
        ),
        migrations.AddField(
            model_name='vacuna',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='condiciones_almacenamiento',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='contraindicaciones',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('En tránsito', 'En tránsito'), ('En cuarentena', 'En cuarentena')], default='Disponible', max_length=255),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='fabricante',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='fecha_caducidad',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='indicaciones',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='lote',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='metodo_preparacion',
            field=models.CharField(choices=[('Inyección', 'Inyección'), ('Oral', 'Oral'), ('Aerosol', 'Aerosol')], default='Inyección', max_length=255),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='objetivo_vacunacion',
            field=models.CharField(choices=[('Prevención de enfermedades infecciosas', 'Prevención de enfermedades infecciosas'), ('Inmunización contra parásitos', 'Inmunización contra parásitos'), ('Inmunización contra alergias', 'Inmunización contra alergias')], default='Prevención de enfermedades infecciosas', max_length=255),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='reacciones_adversas',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='tipo_antigeno',
            field=models.CharField(choices=[('Virus vivo atenuado', 'Virus vivo atenuado'), ('Virus inactivado', 'Virus inactivado'), ('Proteína recombinante', 'Proteína recombinante')], default='Virus vivo atenuado', max_length=255),
        ),
    ]
