# Generated by Django 4.2.5 on 2023-10-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionVacunas', '0002_remove_vacuna_cantidad_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacuna',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='vacunas/'),
        ),
    ]
