# Generated by Django 4.2.5 on 2023-10-25 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionVacunas', '0003_vacuna_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacuna',
            old_name='cantidad',
            new_name='cantidad_disponible',
        ),
    ]
