# Generated by Django 4.2.5 on 2023-09-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datosRecetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreVeterinario', models.CharField(max_length=50)),
                ('nombrePaciente', models.CharField(max_length=50)),
                ('pesoPaciente', models.CharField(max_length=50)),
                ('edadpaciente', models.CharField(max_length=50)),
                ('proximoControl', models.DateField()),
                ('descripcion', models.CharField(max_length=500)),
                ('medicamento', models.CharField(max_length=500)),
                ('dosis', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
                ('firma', models.ImageField(upload_to='Recetas/')),
            ],
        ),
    ]
