# Generated by Django 4.2.5 on 2023-09-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datosClinicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreClinica', models.CharField(max_length=50)),
                ('numeroRegistro', models.CharField(max_length=200)),
                ('aniosFuncionando', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('logo', models.ImageField(upload_to='images/')),
                ('ubicacionLat', models.CharField(max_length=64)),
                ('ubicacionLng', models.CharField(max_length=64)),
            ],
        ),
    ]
