# Generated by Django 4.2.2 on 2023-06-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionClinicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosclinicas',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='datosclinicas',
            name='nombreClinica',
            field=models.CharField(max_length=50),
        ),
    ]
