# Generated by Django 4.2.5 on 2023-09-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionClinicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosclinicas',
            name='nombreClinica',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datosclinicas',
            name='numeroRegistro',
            field=models.CharField(max_length=50),
        ),
    ]
