# Generated by Django 4.2.5 on 2023-10-24 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloGestionExpedientes.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_paciente', models.ImageField(upload_to='pacientes/')),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sexo', models.CharField(max_length=9)),
                ('color', models.CharField(max_length=25)),
                ('nombre_dueño', models.CharField(max_length=200)),
                ('apellido_dueño', models.CharField(max_length=200)),
                ('dui', models.CharField(max_length=9)),
                ('fecha_nacimiento_dueño', models.DateField()),
                ('edad_dueño', models.IntegerField(editable=False, null=True)),
                ('direccion_dueño', models.CharField(max_length=200)),
                ('numero_telefono_dueño', models.CharField(max_length=8)),
                ('correo_electronico_dueño', models.EmailField(max_length=200)),
                ('persona_que_registro', models.CharField(max_length=200)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('departamento_dueño', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moduloGestionExpedientes.departamento')),
                ('municipio_dueño', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moduloGestionExpedientes.municipio')),
            ],
        ),
    ]
