# Generated by Django 4.2.5 on 2023-09-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
