# Generated by Django 4.2.5 on 2023-09-20 03:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionExpedientes', '0002_remove_expediente_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='correo_electronico_dueño',
            field=models.EmailField(default='example@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='expediente',
            name='direccion_dueño',
            field=models.CharField(default='Dirección de ejemplo', max_length=200),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='expediente',
            name='imagen_paciente',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes/'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='nombre_dueño',
            field=models.CharField(default='Nombre de ejemplo', max_length=100),
        ),
        migrations.AddField(
            model_name='expediente',
            name='numero_telefono_dueño',
            field=models.CharField(default='555-123-4567', max_length=20),
        ),
        migrations.AddField(
            model_name='expediente',
            name='ultima_visita',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='raza',
            field=models.CharField(max_length=100),
        ),
    ]
