# Generated by Django 4.2.5 on 2023-09-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionExpedientes', '0004_alter_expediente_correo_electronico_dueño_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='imagen_paciente',
            field=models.ImageField(default='default.jpg', upload_to='pacientes/'),
        ),
    ]
