# Generated by Django 4.2.5 on 2023-09-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionExpedientes', '0005_alter_expediente_imagen_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='correo_electronico_dueño',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='nombre_dueño',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='numero_telefono_dueño',
            field=models.CharField(max_length=8),
        ),
    ]
