# Generated by Django 4.2.5 on 2023-09-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionExpedientes', '0006_alter_expediente_correo_electronico_dueño_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expediente',
            old_name='ultima_visita',
            new_name='ultima_actualizacion',
        ),
        migrations.AddField(
            model_name='expediente',
            name='ultima_vista',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
