# Generated by Django 4.2.5 on 2023-09-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionExpedientes', '0007_rename_ultima_visita_expediente_ultima_actualizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='ultima_vista',
        ),
        migrations.AddField(
            model_name='expediente',
            name='apellido_dueño',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='expediente',
            name='color',
            field=models.CharField(default='N/A', max_length=25),
        ),
        migrations.AddField(
            model_name='expediente',
            name='departamento_dueño',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='expediente',
            name='dui',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='expediente',
            name='edad_dueño',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_nacimiento_dueño',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='municipio_dueño',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='expediente',
            name='persona_que_registro',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='expediente',
            name='sexo',
            field=models.CharField(default='N/A', max_length=9),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='correo_electronico_dueño',
            field=models.EmailField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='direccion_dueño',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='especie',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha_nacimiento',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='imagen_paciente',
            field=models.ImageField(default='default_image.jpg', upload_to='pacientes/'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='nombre_dueño',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='nombre_paciente',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='numero_telefono_dueño',
            field=models.CharField(default='N/A', max_length=8),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='raza',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
