# Generated by Django 4.2.5 on 2023-09-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionExpedientes', '0008_remove_expediente_ultima_vista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='apellido_dueño',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='color',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='correo_electronico_dueño',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='departamento_dueño',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='direccion_dueño',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='dui',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='edad_dueño',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='especie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha_nacimiento_dueño',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='imagen_paciente',
            field=models.ImageField(upload_to='pacientes/'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='municipio_dueño',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='nombre_dueño',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='nombre_paciente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='numero_telefono_dueño',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='persona_que_registro',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='raza',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='sexo',
            field=models.CharField(max_length=9),
        ),
    ]
