# Generated by Django 4.2.5 on 2023-09-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionExpedientes', '0010_alter_expediente_edad_dueño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='dui',
            field=models.CharField(max_length=9),
        ),
    ]
