# Generated by Django 4.2.5 on 2023-10-04 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionExpedientes', '0011_alter_expediente_dui'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='numero_telefono_dueño',
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloGestionExpedientes.departamento')),
            ],
        ),
        migrations.AlterField(
            model_name='expediente',
            name='departamento_dueño',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moduloGestionExpedientes.departamento'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='municipio_dueño',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moduloGestionExpedientes.municipio'),
        ),
    ]
