# Generated by Django 4.2.5 on 2023-10-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionExpedientes', '0012_departamento_remove_expediente_numero_telefono_dueño_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='numero_telefono_dueño',
            field=models.CharField(default='00000000', max_length=8),
        ),
    ]
