# Generated by Django 4.2.5 on 2023-10-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionExpedientes', '0013_expediente_numero_telefono_dueño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='numero_telefono_dueño',
            field=models.CharField(max_length=8),
        ),
    ]
