# Generated by Django 4.2.2 on 2023-06-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionServicios', '0002_alter_datosservicios_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosservicios',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
