# Generated by Django 4.2.5 on 2023-10-24 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moduloGestionMedicamentos', '__first__'),
        ('moduloGestionVeterinarios', '__first__'),
        ('moduloGestionExpedientes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_consulta', models.CharField(default='', max_length=255)),
                ('motivo', models.TextField(default='')),
                ('diagnostico', models.TextField(default='')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloGestionExpedientes.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_utilizada', models.PositiveIntegerField(blank=True, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloGestionConsultas.consulta')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloGestionMedicamentos.medicamento')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='medicamentos',
            field=models.ManyToManyField(through='moduloGestionConsultas.ConsultaMedicamento', to='moduloGestionMedicamentos.medicamento'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloGestionVeterinarios.medicosvet'),
        ),
    ]
