# Generated by Django 4.2.5 on 2023-10-25 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionVacunas', '0003_vacuna_imagen'),
        ('moduloGestionConsultas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_utilizada', models.PositiveIntegerField(blank=True, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloGestionConsultas.consulta')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloGestionVacunas.vacuna')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='consulta',
            name='vacunas',
            field=models.ManyToManyField(through='moduloGestionConsultas.ConsultaVacuna', to='moduloGestionVacunas.vacuna'),
        ),
    ]
