# Generated by Django 4.2.5 on 2023-10-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('dosis', models.DecimalField(decimal_places=2, max_digits=3)),
                ('frecuencia', models.CharField(max_length=255)),
                ('cantidad_disponible', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='medicamentos/')),
            ],
        ),
    ]
