# Generated by Django 4.2.5 on 2023-10-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionMedicamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='frecuencia',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='condiciones_almacenamiento',
            field=models.CharField(default='No hay condiciones de almacenamiento registradas.', max_length=255),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='contraindicaciones',
            field=models.TextField(default='No hay contraindicaciones registradas.'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='denominacion_comun',
            field=models.CharField(default='No hay denominación común registrada.', max_length=255),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='fabricante',
            field=models.CharField(default='No hay fabricante registrado.', max_length=255),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='fecha_caducidad',
            field=models.DateField(default='2018-01-01'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='forma_farmaceutica',
            field=models.CharField(choices=[('Capsula', 'Cápsula'), ('Tableta', 'Tableta'), ('Solucion', 'Solución')], default='Tableta', max_length=255),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='indicaciones',
            field=models.TextField(default='No hay indicaciones registradas.'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='lote',
            field=models.CharField(default='No hay lote registrado.', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='reacciones_adversas',
            field=models.TextField(default='No hay reacciones adversas registradas.'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='tamano',
            field=models.CharField(default='No hay tamaño registrado.', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='dosis',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
