# Generated by Django 4.2.5 on 2023-10-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionMedicamentos', '0002_remove_medicamento_frecuencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='cantidad_utilizada',
            field=models.IntegerField(default=0),
        ),
    ]
