# Generated by Django 4.2.5 on 2023-10-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionMedicamentos', '0003_medicamento_cantidad_utilizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='cantidad_utilizada',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
