# Generated by Django 4.2.5 on 2023-10-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionMedicamentos', '0004_alter_medicamento_cantidad_utilizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='descripcion',
            field=models.TextField(default='No hay descripción registrada.'),
        ),
    ]
