# Generated by Django 4.2.5 on 2023-10-25 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloGestionMedicamentos', '0005_alter_medicamento_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='descripcion',
        ),
    ]
