# Generated by Django 4.2.4 on 2023-09-24 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moduloGestionExpedientes', '0011_alter_expediente_dui'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsquemaVacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moduloGestionExpedientes.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_aplicacion', models.DateField()),
                ('nombre_vacuna', models.CharField(max_length=200)),
                ('fecha_de_proxima_aplicacion', models.DateField()),
                ('persona_que_registro', models.CharField(max_length=200)),
                ('esquemaVacunaciom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloGestionEsquemaVacunacion.esquemavacunacion')),
            ],
        ),
    ]
